/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BetterBalls(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/4_Mirror_Balls.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cilindro3.geometry} material={nodes.Cilindro3.material} />
      <mesh geometry={nodes['100In'].geometry} material={nodes['100In'].material} />
      <mesh geometry={nodes.Cilindro2.geometry} material={nodes.Cilindro2.material} />
      <mesh geometry={nodes['75In'].geometry} material={nodes['75In'].material} />
      <mesh geometry={nodes['75'].geometry} material={nodes['75'].material} />
      <mesh geometry={nodes.Cilindro.geometry} material={nodes.Cilindro.material} />
      <mesh geometry={nodes['50In'].geometry} material={nodes['50In'].material} />
      <mesh geometry={nodes['50'].geometry} material={nodes['50'].material} />
      <mesh geometry={nodes.Cilindro1.geometry} material={nodes.Cilindro1.material} />
      <mesh geometry={nodes['25In'].geometry} material={nodes['25In'].material} />
      <mesh geometry={nodes['25'].geometry} material={nodes['25'].material} />
    </group>
  )
}

useGLTF.preload('/4_Mirror_Balls.gltf')
