/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Balls(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/4_Mirror_Balls_2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/4_Mirror_Balls_2.gltf')
